[noauth.oidc]
issuer = "http://noauth"

[noauth.default]
given_name = "Alice"
family_name = "Edwards"
email = "alice@example.com"
preferred_username = "alice"
roles = ["admin"]

[noauth.token]
aud = "client_id"
scope = "demo"
