[noauth.oidc]
issuer = "http://noauth"

[noauth.client]
client_id = "wordpress"
client_secret = "asdfasdfasdf"
id_token_signed_response_alg = "ES256"

[noauth.default]
given_name = "Alice"
family_name = "Edwards"
email = "alice@example.com"
preferred_username = "alice"
roles = ["admin"]

[noauth.scopes.test]
test = "asdf"

[noauth.token]
aud = "client_id"
scope = "demo"
